[bundle.apu]
github = "giellalt/keyboard-apu"
layouts = ["apu"]

[bundle.bxr]
github = "giellalt/keyboard-bxr"
layouts = ["bxr"]

[bundle.crk]
github = "giellalt/keyboard-crk"
layouts = ["crk", "crk-Cans"]

[bundle.mdf]
github = "giellalt/keyboard-mdf"
layouts = ["mdf"]

[bundle.myv]
github = "giellalt/keyboard-myv"
layouts = ["myv"]

[bundle.nno]
github = "giellalt/keyboard-nno"
layouts = ["nn", "nn-Runr"]

[bundle.sjd]
github = "giellalt/keyboard-sjd"
layouts = ["sjd"]

[bundle.sma]
github = "giellalt/keyboard-sma"
layouts = ["sma"]

[bundle.sme]
github = "giellalt/keyboard-sme"
layouts = ["se"]

[bundle.smj]
github = "giellalt/keyboard-smj"
layouts = ["smj-NO", "smj-SE"]

[bundle.smn]
github = "giellalt/keyboard-smn"
layouts = ["smn"]

[bundle.sms]
github = "giellalt/keyboard-sms"
layouts = ["sms"]

[bundle.srs]
github = "giellalt/keyboard-srs"
layouts = ["srs"]
