locales:
  en:
    name: "Divvun Dev Keyboards"
    description: "Beta Keyboards for minority and indigenous languages from the Divvun group at UiT."
  fi:
    name: "Divvun Dev-näppäimistöt"
    description: "Vähemmistö- ja alkuperäiskielten kielten beta-näppäimistöt Tromssan yliopiston Divvun-ryhmältä."
  'no':
    name: "Divvun Dev-tastaturer"
    description: "Beta-tastaturer for minoritets- og urfolksspråk fra Divvun-gruppa ved UiT."
  nb:
    name: "Divvun Dev-tastaturer"
    description: "Beta-tastaturer for minoritets- og urfolksspråk fra Divvun-gruppa ved UiT."
  nn:
    name: "Divvun Dev-tastatur"
    description: "Beta-tastatur for minoritets- og urfolksspråk frå Divvun-gruppa ved UiT."
  se:
    name: "Divvun Dev boallobeavddit"
    description: "Unnitlogu- ja eamiálbmotgielaid beta-boallobeavddit maid Divvun-joavku UiT:s lea ráhkadan."
  smj:
    name: "Divvun-boallobievde"
    description: "Unneplågo- ja iemeálmmukgiela beta-boallobievde majt Divvun-juogos UiT:an la dahkam."
  sv:
    name: "Divvun Dev-tangentbord"
    description: "Beta-tangentbord för minoritets- och urfolksspråk från Divvun-gruppen vid UiT."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2015-2020 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta
