locales:
  en:
    name: "Divvun Dev Keyboards"
    description: "Beta Keyboards for minority and indigenous languages from the Divvun group at UiT."
  fi:
    name: "Divvun Dev-näppäimistöt"
    description: "Vähemmistö- ja alkuperäiskielten kielten beta-näppäimistöt Tromssan yliopiston Divvun-ryhmältä."
  'no':
    name: "Divvun Dev-tastaturer"
    description: "Beta-tastaturer for minoritets- og urfolksspråk fra Divvun-gruppa ved UiT."
  nb:
    name: "Divvun Dev-tastaturer"
    description: "Beta-tastaturer for minoritets- og urfolksspråk fra Divvun-gruppa ved UiT."
  nn:
    name: "Divvun Dev-tastatur"
    description: "Beta-tastatur for minoritets- og urfolksspråk frå Divvun-gruppa ved UiT."
  ru:
    name: "Клавиатуры Divvun Dev"
    description: "Бета-клавиатуры для языков меньшинств и коренных народов от группы Divvun в UiT."
  se:
    name: "Divvun Dev boallobeavddit"
    description: "Unnitlogu- ja eamiálbmotgielaid beta-boallobeavddit maid Divvun-joavku UiT:s lea ráhkadan."
  smj:
    name: "Divvun-boallobievde"
    description: "Unneplågo- ja iemeálmmukgiela beta-boallobievde majt Divvun-juogos UiT:an la dahkam."
  sv:
    name: "Divvun Dev-tangentbord"
    description: "Beta-tangentbord för minoritets- och urfolksspråk från Divvun-gruppen vid UiT."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2015-2020 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

dependencies:
  aan:
    url: "giellalt/keyboard-aan"
    layouts: ["aan"]
  apu:
    url: "giellalt/keyboard-apu"
    layouts: ["apu"]
  bwi:
    url: "giellalt/keyboard-bwi"
    layouts: ["bwi"]
  bxr:
    url: "giellalt/keyboard-bxr"
    layouts: ["bxr"]
  crk:
    url: "giellalt/keyboard-crk"
    layouts: ["crk", "crk-Cans", "crk-x-macron"]
  fao:
    url: "giellalt/keyboard-fao"
    layouts: ["fo"]
  fit:
    url: "giellalt/keyboard-fit"
    layouts: ["fit"]
  fkv:
    url: "giellalt/keyboard-fkv"
    layouts: ["fkv"]
  gvp:
    url: "giellalt/keyboard-gvp"
    layouts: ["gvp"]
  krl:
    url: "giellalt/keyboard-krl"
    layouts: ["krl"]
  liv:
    url: "giellalt/keyboard-liv"
    layouts: ["liv"]
  lut:
    url: "giellalt/keyboard-lut"
    layouts: ["lut"]
  mdf:
    url: "giellalt/keyboard-mdf"
    layouts: ["mdf"]
  mpu:
    url: "giellalt/keyboard-mpu"
    layouts: ["mpu"]
  myu:
    url: "giellalt/keyboard-myu"
    layouts: ["myu"]
  myv:
    url: "giellalt/keyboard-myv"
    layouts: ["myv"]
  nno:
    url: "giellalt/keyboard-nno"
    layouts: ["nn", "nn-Runr"]
  olo:
    url: "giellalt/keyboard-olo"
    layouts: ["olo"]
  pad:
    url: "giellalt/keyboard-pad"
    layouts: ["pad"]
  pur:
    url: "giellalt/keyboard-pur"
    layouts: ["pur"]
  rmn:
    url: "giellalt/keyboard-rmn"
    layouts: ["rmn"]
  sjd:
    url: "giellalt/keyboard-sjd"
    layouts: ["sjd"]
  sje:
    url: "giellalt/keyboard-sje"
    layouts: ["sje"]
  sju:
    url: "giellalt/keyboard-sju"
    layouts: ["sju"]
  skf:
    url: "giellalt/keyboard-skf"
    layouts: ["skf"]
  sma:
    url: "giellalt/keyboard-sma"
    layouts: ["sma"]
  sme:
    url: "giellalt/keyboard-sme"
    layouts: ["se"]
  smj:
    url: "giellalt/keyboard-smj"
    layouts: ["smj-NO", "smj-SE"]
  smn:
    url: "giellalt/keyboard-smn"
    layouts: ["smn"]
  sms:
    url: "giellalt/keyboard-sms"
    layouts: ["sms"]
  srs:
    url: "giellalt/keyboard-srs"
    layouts: ["srs"]
  tqb:
    url: "giellalt/keyboard-tqb"
    layouts: ["tqb"]
  txi:
    url: "giellalt/keyboard-txi"
    layouts: ["txi"]
  waw:
    url: "giellalt/keyboard-waw"
    layouts: ["waw"]
  wyr:
    url: "giellalt/keyboard-wyr"
    layouts: ["wyr"]
